apiVersion: v1
kind: Service
metadata:
  name: jenkinsdemo
  labels:
    name: jenkinsdemo
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
    nodePort: 30000
  selector:
    name: jenkinsdemo                     